# Generated by Django 5.2 on 2025-04-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uname', models.CharField(default='未填写', max_length=50, unique=True)),
                ('username1', models.CharField(max_length=50, unique=True)),
                ('password1', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('password2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_password', to='users.userinfo')),
                ('username2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_username', to='users.userinfo')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_infor',
            },
        ),
    ]
