# Generated by Django 5.2 on 2025-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='password2',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='username2',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
